site_description: "Vue.js - The Progressive JavaScript Framework"
google_analytics: UA-46852172-1
root_domain: vuejs.org
vue_version: 2.5.13

platinum_sponsors:
  - url: https://stdlib.com
    img: stdlib.png
  - url: http://tooltwist.com/
    img: tooltwist.png
  - url: https://www.infinitynewtab.com/donate/index.html
    img: infinitynewtab.png
  - url: https://vueschool.io/?utm_source=Vuejs.org&utm_medium=Banner&utm_campaign=Sponsored%20Banner&utm_content=V1
    img: vueschool.png
